### ISSUE TITLE
Regarding some common features

### ISSUE THREAD

**Issue by jxnx888** [joe223/tiny-swiper#11]
**Such as slidesPerView, nextButton, prevButton.**
In your project, you only have the Pagination plugin, in Mobile we might use the slidesPerView, nextButton, prevButton.
I think those are the  common features you might have.

**Comment by joe223** [comment]
Thanks for all feedback.

It dose take more time to add  `slidesPerView`,  this will breaks core implementation (I'm trying to keep tiny-swiper smaller than 3kb).

The reason why I didn't create `nextButton` and `prevButton` just because they are too simple —— call `scroll` function（that's all). And, I guess most of user will not use the default nextButton/prevButton style. So it got lower priority.

**Comment by jxnx888** [comment]
Yeah, I totaly understand you. Thanks Joe.

**Comment by dlewand691** [comment]
2 features that would be key for me is variable height and keyboard controls.

**Comment by joe223** [comment]
I guess `variable height` could be implemented by slidesPerView.

@dlewand691 Would you mind to create a new issue for describing the details of keyboard controls?

**Comment by joe223** [comment]
- [x] slidesPerView
- [ ] keyboard controls

**Comment by joe223** [comment]
@dlewand691 @jxnx888 

https://github.com/joe223/tiny-swiper/blob/dev/CHANGELOG.md 1.3.0 released
