### ISSUE TITLE
Add "destroy" method

### ISSUE THREAD

**Issue by r0skar** [joe223/tiny-swiper#3]
**Is your feature request related to a problem? Please describe.**
Using the swiper in a SPA, the Swiper instances are never destroyed as there are no real page-reloads.

**Describe the solution you'd like**
Implement the `destroy` method from SwiperJS.

**Additional context**
See https://swiperjs.com/api/ for more details on the `destroy` API.

**Comment by joe223** [comment]
The challenge for me is that I have to make a trade-off between package size and API richness. We will deviation from purpose if it is too large, it will be useless if lack of important APIs, either.
So, I've thinking of extracting `destroy` events-hub and life hooks (both of them are not completed)  to components, just use them whenever you need. Otherwise, It will grow larger than 3kB someday and more.

**Comment by joe223** [comment]
@northkode You are right, I'll move `destroy` to core API.

**Comment by joe223** [comment]
The draft https://github.com/joe223/tiny-swiper/blob/317b3c037b57c56383f0fe74267ea0073720c282/src/index.js#L462-L482

**Comment by joe223** [comment]
Resolved at https://github.com/joe223/tiny-swiper/pull/6
