### ISSUE TITLE
Breakpoints implementation

### ISSUE THREAD

**Issue by neo773** [joe223/tiny-swiper#70]
Hi there, I was looking through the Documentation and couldn't find a breakpoint parameter that Swiper offers. The library is literally unusable on mobile without this parameter.

`
breakpoints: {
    320: {
        slidesPerView: 1,
        spaceBetween: 20
    },
    480: {
        slidesPerView: 1,
        spaceBetween: 30
    },
    1112: {
        slidesPerView: 3,
        spaceBetween: 30
    },
    1536: {
        slidesPerView: 3,
        spaceBetween: 0
    }
}
`

**Comment by pryley** [comment]
Why not do something like this?

```js
const breakpoints = {
  320: {
    slidesPerView: 1,
    spaceBetween: 20,
  },
  480: {
    slidesPerView: 1,
    spaceBetween: 30,
  },
  1112: {
    slidesPerView: 3,
    spaceBetween: 30,
  },
  1536: {
    slidesPerView: 3,
    spaceBetween: 0,
  }
}

const swiper = new Swiper('.swiper-container');

const swiperResize = () => {
  const width = swiper.env.element.$el.clientWidth
  for (const [breakpoint, options] of Object.entries(breakpoints)) {
    if (width <= breakpoint) {
      swiper.options = Object.assign(swiper.options, options)
      break
    }
  }
  swiper.updateSize()
}

const swiperResizeListener = _.debounce(swiperResize, 200)

window.addEventListener('resize', swiperResizeListener, { passive: true })

swiper.on('after-init', swiperResize)
swiper.on('after-destroy', () => window.removeEventListener('resize', swiperResizeListener)
```

**Comment by pryley** [comment]
@joe223 

What about creating an official plugin for breakpoints?

I started a basic implementation but have not tested it. It includes a built-in debounce: https://gist.github.com/pryley/3bc6d2f01aa5b68f829a5fbeb19abbd8

A few caveats:

1. It does not take swiper direction into account
2. You may need to convert to Typescript
3. It assumes that the breakpoints object is in the format above.

**Comment by joe223** [comment]
@pryley That's really great！Here are some questions I considered about

1. Try using `env.measure` instead of `element`, avoid access real DOM data in `state` Layer. That's means you are exactly right, `instance.env.measure.viewSize` would be better!
2. Definitely yes
3. I think it's does not matter if treat breakpoints‘s format as a Pact/Convention
4. An option should be better
5. It won't break the program if `{ passive: true }` is not supported

Btw, would it be better if we provide `throttle` and `debounce` as common utils?

**Comment by pryley** [comment]
@joe223 

1. The only reason I didn't use `instance.env.measure.viewSize` was because that value can represent either the width or height depending on the direction of the swiper.
2. You would need to help with this as I'm not familiar with Typescript
 
Regarding throttle and debounce, it could be useful to provide these as utils if they are only imported as needed. The debounce implementation I used is stripped down from the lodash implementation.

**Comment by joe223** [comment]
@pryley So, the `breakpoints`  is only for horizontal direction right? 🤔

**Comment by pryley** [comment]
Yes. The resize event is triggered by the window, but the breakpoint size is defined by the swiper width, not the window size.

How would you suggest this otherwise?

**Comment by joe223** [comment]
@pryley How about adding a new property of `measure` which means the another dimension of view size and cross with slide direction?

**Comment by pryley** [comment]
I'm not sure vertical breakpoints would be useful. I think you would be more likely to use a breakpoints feature to _change_ the direction of a swiper rather than to determine if a breakpoint is triggered by vertical or horizontal resizing. The reason measuring by width is more practical is because 90% of all devices that allow you to free-resize a browser window (i.e. desktop devices) have landscape screens.

What if we simply mirrored the breakpoint functionality of swiperjs? It provides two options:

- `breakpoints`: params object
- `breakpointsBase`: enom string ("window" or "container")

It only measures width on resize, not height. The breakpoint keys can be either integer units (as pixels) or ratio strings (i.e. "@0.75"), however I think to keep it minimal only integer unit are really necessary.



https://swiperjs.com/swiper-api#param-breakpoints

**Comment by joe223** [comment]
@pryley Great, I'll get this done in Oct

**Comment by joshauh46** [comment]
@joe223 Any updates on this?

**Comment by joe223** [comment]
Hi @pryley @joshauh46 , sorry for the late reply. `2.2.0` was released. API: https://tiny-swiper.js.org/docs/api#breakpoints. Demo: https://tiny-swiper.js.org/docs/demo#breakpoints
